global:
  smtp_smarthost: 'localhost:1025'

route:
  group_by: ['alerts']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'webhook'

receivers:
  - name: 'webhook'
    webhook_configs:
      - url: 'http://localhost:5000/'
        send_resolved: true