global:
  scrape_interval: 3s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'wbordersaver'
    metrics_path: /metrics
    static_configs:
      - targets: ['wbordersaver:8082']
    scrape_interval: 5s

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]


alerting:
  alertmanagers:
    - static_configs:
        - targets: [ 'alertmanager:9095' ]
